databases:
  - name: monstermania
    plan: free
    databaseName: monstermania
    user: canis
    region: frankfurt

services:
  - type: web
    plan: free
    name: monstermania
    region: frankfurt
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn monstermania.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: monstermania
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
