# Generated by Django 5.0.4 on 2024-05-05 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='snacks',
        ),
        migrations.RemoveField(
            model_name='game',
            name='poison_rate',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='log',
            name='game',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.DeleteModel(
            name='Snack',
        ),
    ]
